# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: b07
  description: Final Android Project for CSCB07 
  private: true
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_vulnerability_alerts: true

labels:
  - name: good first issue
    color: '#a68cd9'
    description: Good for newcomers

  - name: fix
    color: '#ff6680'
    description: Bug was put on trial and executed

  - name: feat
    color: '#39c5bb'
    description: New feature has joined chat

  - name: refactor
    color: '#ffe666'
    description: Cedo has beomce mroe raedebla tahn eevr bofree

  - name: doc
    color: '#66ccff'
    description: For programmers with short memory (i.e. me)

  - name: chore
    color: '#d7d7d7'
    description: Happy compiler, happy life

  - name: perf
    color: '#ff9966'
    description: I am speed
    
collaborators:
  - username: Forma-Lin
  - username: TheRealSpaghetti

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions: null
        
