name: Android CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - run: mv app/build/outputs/apk/debug/app-debug.apk b07.apk
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: b07.apk
